GET https://localhost:5001/api/students/1
Accept: */*
Cache-Control: no-cache

###

GET https://localhost:5001/api/students?orderBy=LOL
Accept: */*
Cache-Control: no-cache

###

POST https://localhost:5001/api/students
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "idStudent": 1,
  "firstName": "Marek",
  "lastName": "Lewandowski"
}

###

PUT https://localhost:5001/api/students
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "idStudent": 1,
  "firstName": "Marek",
  "lastName": "Lewandowski"
}

###

DELETE https://localhost:5001/api/students/1
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

###

GET https://localhost:5001/api/students/1/enrollments
Index: s1234
Accept: */*
Cache-Control: no-cache

###

POST  https://localhost:5001/api/enrollments HTTP/1.1
Content-Type: application/json

{
  "IndexNumber": "s13421",
  "FirstName": "Andrzej",
  "LastName": "Malewski",
  "BirthDate": "1995-06-18",
  "Studies": "IT"
}

###

POST https://localhost:5001/api/enrollments/promotions
Content-Type: application/json

{
  "Studies": "IT",
  "Semester": 1
}